namespace GTA_SA_Effect_Editor
{
    public static class Autocomplete
    {
        public static string[] PRIM { get; set; } = new string[]
        {
            "FX_SYSTEM_DATA",
            "FILENAME",
            "NAME",
            "LENGTH",
            "PLAYMODE",
            "CULLDIST",
            "BOUNDINGSPHERE",
            "NUM_PRIMS",
            "FX_PRIM_EMITTER_DATA",
            "FX_PRIM_BASE_DATA",
            "MATRIX",
            "TEXTURE",
            "TEXTURE2",
            "TEXTURE3",
            "TEXTURE4",
            "ALPHAON",
            "SRCBLENDID",
            "DSTBLENDID",
            "NULL",
            "NUM_INFOS",
            "LODSTART",
            "LODEND",
            "OMITTEXTURES",
            "TXD",
            "NOTXDSET",
            "FX_INFO_SIZE_DATA",
            "FX_INFO_EMLIFE_DATA",
            "FX_INFO_EMRATE_DATA",
            "FX_INFO_EMSPEED_DATA",
            "FX_INFO_EMANGLE_DATA",
            "FX_INFO_FORCE_DATA",
            "FX_INFO_ROTSPEED_DATA",
            "FX_INFO_COLOURBRIGHT_DATA",
            "FX_INFO_EMROTATION_DATA",
            "FX_INFO_EMDIR_DATA",
            "FX_INFO_EMSIZE_DATA",
            "FX_INFO_COLOUR_DATA",
            "FX_INFO_FRICTION_DATA",
            "FX_INFO_WIND_DATA",
            "FX_INFO_SELFLIT_DATA",
            "FX_INFO_DIR_DATA",
            "FX_INFO_HEATHAZE_DATA",
            "FX_INFO_SPRITERECT_DATA",
            "FX_INFO_JITTER_DATA",
            "FX_INFO_FLAT_DATA",
            "FX_INFO_EMPOS_DATA",
            "FX_INFO_FLOAT_DATA",
            "FX_INFO_NOISE_DATA",
            "FX_INFO_UNDERWATER_DATA",
            "FX_INFO_TRAIL_DATA",
            "FX_INFO_GROUNDCOLLIDE_DATA",
            "FX_INFO_ANIMTEX_DATA",
            "FX_INFO_EMWEATHER_DATA",
            "FX_INFO_ATTRACTPT_DATA",
            "TIMEMODEPRT",
            "FX_INTERP_DATA",
            "LOOPED",
            "NUM_KEYS",
            "FX_KEYFLOAT_DATA",
            "TIME",
            "VAL"
        };

        public static string[] INFO { get; set; } = new string[]
        {
            "FX_INTERP_DATA",
            "LOOPED",
            "NUM_KEYS",
            "FX_KEYFLOAT_DATA",
            "TIME",
            "VAL",
            "FX_INFO_ATTRACTPT_DATA",
            "FX_INFO_SIZE_DATA",
            "FX_INFO_EMLIFE_DATA",
            "FX_INFO_EMRATE_DATA",
            "FX_INFO_EMSPEED_DATA",
            "FX_INFO_EMANGLE_DATA",
            "FX_INFO_FORCE_DATA",
            "FX_INFO_ROTSPEED_DATA",
            "FX_INFO_COLOURBRIGHT_DATA",
            "FX_INFO_EMROTATION_DATA",
            "FX_INFO_EMDIR_DATA",
            "FX_INFO_EMSIZE_DATA",
            "FX_INFO_COLOUR_DATA",
            "FX_INFO_FRICTION_DATA",
            "FX_INFO_WIND_DATA",
            "FX_INFO_SELFLIT_DATA",
            "FX_INFO_DIR_DATA",
            "FX_INFO_HEATHAZE_DATA",
            "FX_INFO_SPRITERECT_DATA",
            "FX_INFO_JITTER_DATA",
            "FX_INFO_FLAT_DATA",
            "FX_INFO_EMPOS_DATA",
            "FX_INFO_FLOAT_DATA",
            "FX_INFO_NOISE_DATA",
            "FX_INFO_UNDERWATER_DATA",
            "FX_INFO_TRAIL_DATA",
            "FX_INFO_GROUNDCOLLIDE_DATA",
            "FX_INFO_ANIMTEX_DATA",
            "FX_INFO_EMWEATHER_DATA",
            "TIMEMODEPRT"
        };

        public static string[] INTERP { get; set; } = new string[]
        {
            "FX_INTERP_DATA",
            "LOOPED",
            "NUM_KEYS",
            "FX_KEYFLOAT_DATA",
            "TIME",
            "VAL"
        };

        public static string[] KEYFLOAT { get; set; } = new string[]
        {
            "FX_KEYFLOAT_DATA",
            "TIME",
            "VAL"
        };
    }
}